pull_request_rules:
  - name: Auto-merge approved PRsqq
    conditions:
      - base = main
      - "#approved-reviews-by >= 2"
      - check-success = ci/build
    actions:
      merge:
        method: squash
